const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const express = require('express');

// Route-level security tests for all three logo-upload endpoints
// (POST /users/profile/logo, POST /templates/:id/logo, POST /white-label/logo)
// through the REAL routers, REAL multer limits and the REAL global error
// handler (middleware/errorHandler.js). Only auth/Firestore/Storage and the
// template service are faked. All fixtures are benign images generated by
// sharp, or mislabelled/corrupt copies of them.

const { sharp } = require('../utils/safeImage');
const { errorHandler } = require('../middleware/errorHandler');

const firebaseConfigPath = require.resolve('../config/firebase');
const storagePath = require.resolve('../config/storage');
const templateServicePath = require.resolve('../services/templateService');
const authMiddlewarePath = require.resolve('../middleware/auth');
const routePaths = {
  users: require.resolve('../routes/users'),
  templates: require.resolve('../routes/templates'),
  whitelabel: require.resolve('../routes/whitelabel'),
};

const AUTH_TIME = Math.floor(Date.now() / 1000);
const TEST_UID = 'logo-route-uid';

function installFakes() {
  const uploads = [];
  const userData = { tier: 'enterprise', email: 'logo-test@example.com', tokenVersion: 0 };
  for (const p of [
    firebaseConfigPath,
    storagePath,
    templateServicePath,
    authMiddlewarePath,
    ...Object.values(routePaths),
  ]) {
    delete require.cache[p];
  }
  const docRef = {
    get: async () => ({ exists: true, data: () => userData, ref: docRef }),
    update: async (patch) => Object.assign(userData, patch),
    set: async () => {},
  };
  const query = {
    limit: () => query,
    where: () => query,
    get: async () => ({ empty: true, docs: [] }),
  };
  require.cache[firebaseConfigPath] = {
    id: firebaseConfigPath,
    filename: firebaseConfigPath,
    loaded: true,
    exports: {
      getAuth: () => ({
        verifyIdToken: async () => ({
          uid: TEST_UID,
          email: userData.email,
          auth_time: AUTH_TIME,
          iat: AUTH_TIME,
        }),
      }),
      getFirestore: () => ({
        collection: () => ({
          doc: () => docRef,
          where: () => query,
          add: async () => ({ id: 'fake-id' }),
        }),
      }),
      FieldValue: {},
      Timestamp: {},
      admin: {},
      initFirebase: () => {},
      getBucket: () => {},
    },
  };
  const objectPath = (...parts) => parts.join('/');
  require.cache[storagePath] = {
    id: storagePath,
    filename: storagePath,
    loaded: true,
    exports: {
      logoObject: (uid, name) => objectPath('users', uid, 'logos', name),
      templateLogoObject: (uid, id, name) => objectPath('users', uid, 'templates', id, name),
      whiteLabelObject: (uid, name) => objectPath('users', uid, 'whitelabel', name),
      uploadBuffer: async (p, buffer, contentType) => {
        uploads.push({ path: p, buffer, contentType });
        return { url: `https://storage.example.test/${p}` };
      },
      deleteObject: async () => {},
      deletePrefix: async () => {},
      downloadBuffer: async () => Buffer.alloc(0),
    },
  };
  require.cache[templateServicePath] = {
    id: templateServicePath,
    filename: templateServicePath,
    loaded: true,
    exports: {
      getTemplateForEdit: async () => ({ template: { id: 'tpl-1' } }),
      setTemplateLogo: async (user, id, logo) => ({ template: { id, logo } }),
    },
  };
  const app = express();
  app.use(express.json());
  app.use('/api/users', require(routePaths.users));
  app.use('/api/templates', require(routePaths.templates));
  app.use('/api/white-label', require(routePaths.whitelabel));
  app.use(errorHandler);
  return { app, uploads };
}

async function withServer(app, fn) {
  const server = http.createServer(app);
  await new Promise((resolve) => server.listen(0, resolve));
  const { port } = server.address();
  try {
    await fn(`http://127.0.0.1:${port}`);
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
}

const post = async (url, buffer, mimetype, filename = 'logo.png') => {
  const form = new FormData();
  form.append('logo', new Blob([buffer], { type: mimetype }), filename);
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: 'Bearer faketoken' },
    body: form,
  });
  return { status: res.status, body: await res.json().catch(() => ({})) };
};

const ROUTES = [
  {
    name: 'profile logo',
    path: '/api/users/profile/logo',
    box: [300, 150],
    maxBytes: 2 * 1024 * 1024,
    svg: false,
  },
  {
    name: 'template logo',
    path: '/api/templates/tpl-1/logo',
    box: [400, 200],
    maxBytes: 5 * 1024 * 1024,
    svg: true,
  },
  {
    name: 'white-label logo',
    path: '/api/white-label/logo',
    box: [400, 200],
    maxBytes: 5 * 1024 * 1024,
    svg: true,
  },
];

// ---- fixtures ----------------------------------------------------------------

const rgba = (w, h) =>
  sharp({
    create: { width: w, height: h, channels: 4, background: { r: 200, g: 30, b: 30, alpha: 0.5 } },
  });
const vipsBytes = async () => {
  const file = path.join(os.tmpdir(), `flacron-logo-vips-${process.pid}-${Date.now()}.v`);
  await sharp({ create: { width: 8, height: 8, channels: 3, background: '#fff' } }).toFile(file);
  try {
    return fs.readFileSync(file);
  } finally {
    fs.rmSync(file, { force: true });
  }
};

let fx;
test.before(async () => {
  const base = sharp({ create: { width: 32, height: 32, channels: 3, background: '#445566' } });
  fx = {
    bigPng: await rgba(1200, 400).png().toBuffer(), // 3:1, larger than every box
    smallPng: await rgba(60, 30).png().toBuffer(), // smaller than every box
    jpeg: await base.clone().jpeg().toBuffer(),
    webp: await rgba(80, 40).webp().toBuffer(),
    tiff: await base.clone().tiff().toBuffer(),
    gif: await base.clone().gif().toBuffer(),
    avif: await base.clone().avif().toBuffer(),
    vips: await vipsBytes(),
    svg: Buffer.from(
      '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10"/></svg>'
    ),
  };
});

// ---- per-route tests ---------------------------------------------------------

for (const route of ROUTES) {
  test(`${route.name}: a large transparent PNG is resized inside ${route.box.join('x')}, aspect kept, alpha kept`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const res = await post(base + route.path, fx.bigPng, 'image/png');
      assert.equal(res.status, 200, JSON.stringify(res.body));
      assert.equal(uploads.length, 1);
      const meta = await sharp(uploads[0].buffer).metadata();
      assert.equal(uploads[0].contentType, 'image/png');
      assert.equal(meta.format, 'png');
      assert.equal(meta.width, route.box[0]);
      assert.equal(meta.height, Math.round(route.box[0] / 3));
      assert.ok(meta.height <= route.box[1]);
      assert.equal(meta.hasAlpha, true, 'transparency preserved');
    });
  });

  test(`${route.name}: a small logo is never enlarged; JPEG and WebP are accepted`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const small = await post(base + route.path, fx.smallPng, 'image/png');
      assert.equal(small.status, 200);
      const meta = await sharp(uploads[0].buffer).metadata();
      assert.equal(meta.width, 60);
      assert.equal(meta.height, 30);
      assert.equal((await post(base + route.path, fx.jpeg, 'image/jpeg', 'logo.jpg')).status, 200);
      assert.equal((await post(base + route.path, fx.webp, 'image/webp', 'logo.webp')).status, 200);
    });
  });

  test(`${route.name}: TIFF, VIPS, GIF and AVIF bytes mislabelled as image/png are rejected with 400 and never stored`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      for (const key of ['tiff', 'vips', 'gif', 'avif']) {
        const res = await post(base + route.path, fx[key], 'image/png');
        assert.equal(res.status, 400, `${key}: ${JSON.stringify(res.body)}`);
        assert.equal(res.body.success, false);
        assert.equal(res.body.code, 'UNSUPPORTED_IMAGE_TYPE', key);
        assert.match(res.body.error, /Unsupported image type/);
      }
      assert.equal(uploads.length, 0);
    });
  });

  test(`${route.name}: real JPEG bytes declared as image/png are a 400 type mismatch`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const res = await post(base + route.path, fx.jpeg, 'image/png');
      assert.equal(res.status, 400);
      assert.equal(res.body.code, 'IMAGE_TYPE_MISMATCH');
      assert.equal(uploads.length, 0);
    });
  });

  test(`${route.name}: corrupt and truncated PNGs are rejected with a clear 400`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const corrupt = Buffer.concat([fx.bigPng.subarray(0, 8), Buffer.alloc(64, 0x41)]);
      const res = await post(base + route.path, corrupt, 'image/png');
      assert.equal(res.status, 400);
      assert.equal(res.body.code, 'IMAGE_UNREADABLE');
      const truncated = await post(base + route.path, fx.bigPng.subarray(0, 40), 'image/png');
      assert.equal(truncated.status, 400, JSON.stringify(truncated.body));
      assert.equal(uploads.length, 0);
    });
  });

  test(`${route.name}: an unsupported declared type is a clear 400 (not a 500)`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const res = await post(base + route.path, fx.gif, 'image/gif', 'logo.gif');
      assert.equal(res.status, 400, JSON.stringify(res.body));
      assert.equal(res.body.code, 'UNSUPPORTED_IMAGE_TYPE');
      assert.match(res.body.error, /^Only /);
      assert.equal(uploads.length, 0);
    });
  });

  test(`${route.name}: files over the ${route.maxBytes / (1024 * 1024)} MB limit are rejected with 413`, async () => {
    const { app, uploads } = installFakes();
    await withServer(app, async (base) => {
      const oversized = Buffer.concat([
        fx.bigPng,
        Buffer.alloc(route.maxBytes + 1 - fx.bigPng.length),
      ]);
      const res = await post(base + route.path, oversized, 'image/png');
      assert.equal(res.status, 413);
      assert.equal(res.body.code, 'FILE_TOO_LARGE');
      assert.equal(uploads.length, 0);
    });
  });

  if (route.svg) {
    test(`${route.name}: a real SVG is stored as-is; binary bytes labelled image/svg+xml are rejected`, async () => {
      const { app, uploads } = installFakes();
      await withServer(app, async (base) => {
        const ok = await post(base + route.path, fx.svg, 'image/svg+xml', 'logo.svg');
        assert.equal(ok.status, 200, JSON.stringify(ok.body));
        assert.equal(uploads.length, 1);
        assert.equal(uploads[0].contentType, 'image/svg+xml');
        assert.ok(uploads[0].buffer.equals(fx.svg));
        for (const key of ['tiff', 'vips', 'avif', 'bigPng']) {
          const res = await post(base + route.path, fx[key], 'image/svg+xml', 'logo.svg');
          assert.equal(res.status, 400, key);
          assert.equal(res.body.code, 'IMAGE_TYPE_MISMATCH', key);
        }
        assert.equal(uploads.length, 1);
      });
    });
  }
}
