const { PDFDocument, rgb, degrees, StandardFonts } = require('pdf-lib');

// Adds a diagonal text watermark (and optional logo) to a PDF.
// Buffer in → Buffer out (no disk I/O — Render is ephemeral).
const addWatermarkToPDF = async (inputBuffer, text, logoBuffer = null) => {
  try {
    const pdfDoc = await PDFDocument.load(inputBuffer);
    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const pages = pdfDoc.getPages();

    for (const page of pages) {
      const { width, height } = page.getSize();

      if (logoBuffer) {
        try {
          // Try PNG first, fall back to JPG.
          let logoImage;
          try {
            logoImage = await pdfDoc.embedPng(logoBuffer);
          } catch {
            logoImage = await pdfDoc.embedJpg(logoBuffer);
          }
          const logoDims = logoImage.scale(0.3);
          page.drawImage(logoImage, {
            x: width / 2 - logoDims.width / 2,
            y: height / 2 - logoDims.height / 2,
            width: logoDims.width,
            height: logoDims.height,
            opacity: 0.08,
          });
        } catch (logoErr) {
          console.warn('Logo watermark error:', logoErr.message);
        }
      }

      const watermarkText = text || 'Generated by FlacronAI — Upgrade to remove watermark';
      const fontSize = 18;

      for (let i = 0; i < 3; i++) {
        page.drawText(watermarkText, {
          x: width * 0.05,
          y: height * (0.25 + i * 0.25),
          size: fontSize,
          font: helveticaFont,
          color: rgb(0.6, 0.6, 0.6),
          opacity: 0.25,
          rotate: degrees(35),
        });
      }
    }

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  } catch (err) {
    console.error('Watermark error:', err);
    throw err;
  }
};

const addCompanyWatermark = async (inputBuffer, companyName) => {
  return addWatermarkToPDF(inputBuffer, `DRAFT — ${companyName}`, null);
};

module.exports = { addWatermarkToPDF, addCompanyWatermark };
