// Phase 42 (Section 7 Rendering, Editor & Report Integration).
//
// Pure, dependency-free module that turns Phase 41's canonical structured
// estimate into the markdown detail block for Section 7, and REPLACES a
// report's existing (legacy AI-narrative) Section 7 body with it at render
// time only -- the two are never shown together (see injectSection7Detail's
// own header comment for the exact rule and the 2026-09-18 correction).
//
// Architecture decision: properPdfGenerator.js / documentGenerator.js /
// generateHTML (reports.js) all already parse the SAME `##`/`###`/`|...|`/
// `- ` markdown dialect out of `report.content` (this is exactly how the
// existing RepairEstimate/Invoice/CoverageDeterminationLetter deterministic
// documents render -- see estimateContent.js). Rather than teaching all
// three renderers a second, bespoke drawing routine for the detailed
// estimate (tripling the risk of an escaping/pagination/TOC bug across
// three independent code paths), this module produces one normalized
// markdown string from the canonical estimate and splices it into the
// in-memory `content` the export route hands to whichever renderer runs --
// never persisted back to Firestore, so the canonical estimate remains the
// single source of truth (Golden Rule: no second editable total). The
// existing per-line loops in every renderer already handle headings,
// tables (with page-break header repeat), bullets, and text escaping
// correctly and are exercised by their own test suites -- reusing them here
// means Section 7's new detail automatically inherits correct pagination,
// TOC page-tracking (the "## SECTION 7" heading this detail is appended
// beneath is untouched, so recordTocHeadingPage's existing first-occurrence
// logic keeps working), and per-format sanitization (PDFKit draws literal
// text with no markup risk; DOCX escapes every run via escapeXml; HTML
// escapes every run via escapeHtml) with zero new escaping code to audit.
//
// Golden Rule #2/#4: this module never calls AI and never invents a price --
// every dollar figure rendered here was already computed server-side by
// canonicalEstimate.js's computeRollups from adjuster/contractor-entered
// inputs, reused as-is.

const CENTS_PER_DOLLAR = 100;

const formatMoney = (cents, currency = 'USD') => {
  const amount = (Number(cents) || 0) / CENTS_PER_DOLLAR;
  try {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(amount);
  } catch {
    return `$${amount.toFixed(2)}`;
  }
};

// Markdown-table/line-structure safety (NOT an XSS/injection concern -- every
// renderer already escapes text for its own output format downstream; see
// header comment). A raw "|" in user-entered text would silently misalign a
// pipe-table's column count across all three renderers, and a raw newline
// would inject an extra physical line that could itself be mistaken for a
// heading/table/bullet token by the shared per-line parsers. Neither is
// possible once every user-controlled field is passed through this first.
const sanitizeForMarkdown = (text) =>
  String(text ?? '')
    .replace(/\r\n?/g, ' ')
    .replace(/\n/g, ' ')
    .replace(/\|/g, '/')
    .trim();

const REVIEWED_STATUSES_FOR_LABEL = new Set(['finalized', 'approved', 'completed']);

const PRICING_SOURCE_LABELS = {
  manual: 'Manually entered by preparer',
  price_list: 'Price list lookup',
  historical: 'Historical claim data',
  // Phase 43 hook: once AI-suggested pricing lands, this is the only line
  // that needs to change -- Phase 42 itself never sets pricingSource to
  // this value anywhere, so this branch cannot fire yet (no fabricated
  // "AI-generated" claim is possible today).
  ai_suggested: 'Pricing Source generated by: Flacron Engine',
};

// Groups line items by room/area, then by trade (falling back to category
// when trade is blank) -- "graceful fallback... no blank or misleading
// headings" per the Phase 42 spec. Every line item is required to have a
// `room`/`category` by canonicalEstimate.js's own validation, so the
// fallback strings below are defensive, not load-bearing.
const groupLineItems = (lineItems) => {
  const rooms = new Map();
  for (const li of lineItems) {
    const roomKey = sanitizeForMarkdown(li.room) || 'Unspecified Area';
    if (!rooms.has(roomKey)) rooms.set(roomKey, new Map());
    const trades = rooms.get(roomKey);
    const tradeKey = sanitizeForMarkdown(li.trade || li.category) || 'General';
    if (!trades.has(tradeKey)) trades.set(tradeKey, []);
    trades.get(tradeKey).push(li);
  }
  return [...rooms.entries()].map(([room, trades]) => ({
    room,
    trades: [...trades.entries()].map(([trade, items]) => ({ trade, items })),
  }));
};

// Builds the markdown detail block for Section 7. Returns '' (a safe no-op)
// when there is no canonical estimate or it has no line items yet -- the
// legacy-fallback / empty-state contract: callers must never inject an
// empty heading into the report.
const buildSection7DetailMarkdown = (estimate, { reportStatus } = {}) => {
  if (!estimate || !Array.isArray(estimate.lineItems) || estimate.lineItems.length === 0) {
    return '';
  }
  const currency = estimate.currency || 'USD';
  const fmt = (cents) => formatMoney(cents, currency);
  const isFinal = REVIEWED_STATUSES_FOR_LABEL.has(reportStatus);
  const statusLine = isFinal ? 'Status: Final — Approved' : 'Status: Preliminary / Editable';
  const pricingLine = `Pricing Source: ${PRICING_SOURCE_LABELS[estimate.pricingSourceMeta?.source] || PRICING_SOURCE_LABELS.manual}`;

  const parts = [];
  parts.push('### Detailed Repair Estimate Breakdown');
  parts.push(
    [
      `- **${pricingLine}**`,
      `- **${statusLine}**`,
      `- **Estimate Revision:** ${estimate.revision ?? 1}`,
      `- **Currency:** ${currency}`,
    ].join('\n')
  );

  for (const group of groupLineItems(estimate.lineItems)) {
    parts.push(`### Area: ${group.room}`);
    for (const trade of group.trades) {
      parts.push(`**Trade / Category: ${trade.trade}**`);
      const rows = trade.items
        .map((li) => {
          const desc = sanitizeForMarkdown(li.description);
          const action = sanitizeForMarkdown(li.repairAction) || '—';
          const qty = `${li.quantity} ${sanitizeForMarkdown(li.unit)}`;
          return `| ${desc} | ${action} | ${qty} | ${fmt(li.unitPriceCents)} | ${fmt(li.lineTotalCents)} |`;
        })
        .join('\n');
      parts.push(
        `| Description | Repair Action | Qty | Unit Price | Line Total |\n|------|------|------|------|------|\n${rows}`
      );

      const detailBullets = trade.items
        .map((li) => {
          const bits = [`**${sanitizeForMarkdown(li.description)}**`];
          if (li.material) bits.push(`Material: ${sanitizeForMarkdown(li.material)}`);
          const componentBits = [];
          if (li.materialUnitCostCents) componentBits.push(`Material cost ${fmt(li.materialUnitCostCents)}`);
          if (li.laborUnitCostCents) componentBits.push(`Labor cost ${fmt(li.laborUnitCostCents)}`);
          if (li.equipmentUnitCostCents) componentBits.push(`Equipment cost ${fmt(li.equipmentUnitCostCents)}`);
          if (componentBits.length) bits.push(componentBits.join(' · '));
          bits.push(`Taxable: ${li.taxable ? 'Yes' : 'No'}`);
          bits.push(`Confidence: ${sanitizeForMarkdown(li.confidence || 'medium')}`);
          bits.push(`Status: ${sanitizeForMarkdown(li.lineStatus || 'preliminary')}`);
          if (li.userOverride?.active) {
            bits.push(
              `Unit price manually overridden${li.userOverride.reason ? ` (${sanitizeForMarkdown(li.userOverride.reason)})` : ''}`
            );
          }
          if (Array.isArray(li.evidencePhotoIds) && li.evidencePhotoIds.length) {
            bits.push(`Evidence: ${li.evidencePhotoIds.length} photo(s) linked`);
          }
          if (li.assumptions) bits.push(`Assumptions: ${sanitizeForMarkdown(li.assumptions)}`);
          return `- ${bits.join(' · ')}`;
        })
        .join('\n');
      parts.push(detailBullets);
    }
  }

  const t = estimate.totals || {};
  const summaryRows = [
    ['Line-Item Subtotal', t.lineItemSubtotalCents],
    ['Permits', t.permitsTotalCents],
    ['General Conditions', t.generalConditionsTotalCents],
    ['Manual Adjustments', t.manualAdjustmentsTotalCents],
    ['Direct Cost', t.directCostCents],
    [`Overhead & Profit (${t.overheadProfitPercent ?? 0}%)`, t.overheadProfitCents],
    ['Taxable Basis (excludes Overhead & Profit)', t.taxableBasisCents],
    [`Tax (${t.taxRatePercent ?? 0}%)`, t.taxCents],
    ['Total Estimate', t.grandTotalCents],
  ];
  parts.push(
    `### Financial Summary\n| Line Item | Amount |\n|------|------|\n${summaryRows
      .map(([label, cents]) => `| ${label} | ${fmt(cents || 0)} |`)
      .join('\n')}`
  );
  parts.push(
    "*Overhead & profit is calculated on direct cost and is not automatically included in the sales-tax taxable basis under the current calculation rules. Every figure above is computed by the server from the line items entered in the estimate editor -- FlacronAI's AI does not generate, calculate, or determine any dollar amount in this breakdown.*"
  );

  return parts.join('\n\n');
};

// Matches an H2 heading token "SECTION 7" (case-insensitive), the same
// numbered-section convention every AI-narrative document type's Section 7
// heading already uses (properPdfGenerator.js's own SECTION_TOKEN_RE). Only
// H2 (`##`) -- not H3 (`###`) -- so a heading INSIDE this module's own
// injected detail (also using `###`) can never be mistaken for a new
// top-level "Section 7".
const SECTION7_HEADING_RE = /^##\s*SECTION\s+7\b/i;
// A new top-level heading (H1 or exactly H2) that should end Section 7's
// content -- deliberately excludes H3+ so the injected detail's own `###`
// sub-headings are never mistaken for the start of "Section 8".
const NEXT_TOP_LEVEL_HEADING_RE = /^#{1,2}(?!#)\s/;

// REPLACES the body of the FIRST "## SECTION 7..." heading with
// `detailMarkdown` -- everything between that heading line and the next
// top-level heading (or the end of the document, if Section 7 is last) is
// discarded, never retained alongside the canonical detail. This is a
// deliberate correction (2026-09-18 audit): a report must never show BOTH
// the legacy AI-narrative estimate summary and the canonical structured
// breakdown at once -- exactly one Section 7 body is ever rendered. The
// heading line itself is untouched (so the existing dynamic TOC's
// first-occurrence page-tracking keeps working unmodified), and every
// following section (Section 8+) is untouched byte-for-byte. A no-op
// (returns `content` unchanged) when there is no detail to inject, or no
// "SECTION 7" heading is found -- the legacy-fallback / non-estimate
// document-type safety net: this never fabricates a heading, and never
// touches a document whose Section 7 isn't the numbered one at all. Never
// persisted -- the caller (the export route) only ever passes the result
// into a renderer for this one response; the report's own stored `content`
// in Firestore is never written to.
const injectSection7Detail = (content, detailMarkdown) => {
  if (!detailMarkdown) return content;
  const source = String(content || '');
  const lines = source.split('\n');
  const sec7Index = lines.findIndex((line) => SECTION7_HEADING_RE.test(line.trim()));
  if (sec7Index === -1) return content;

  let nextHeadingIndex = lines.length;
  for (let i = sec7Index + 1; i < lines.length; i++) {
    if (NEXT_TOP_LEVEL_HEADING_RE.test(lines[i].trim())) {
      nextHeadingIndex = i;
      break;
    }
  }

  const before = lines.slice(0, sec7Index + 1); // includes the Section 7 heading line itself
  const after = lines.slice(nextHeadingIndex); // Section 8+ (or nothing), untouched
  const spliced = [...before, '', ...detailMarkdown.split('\n'), '', ...after];
  return spliced.join('\n');
};

module.exports = {
  formatMoney,
  sanitizeForMarkdown,
  groupLineItems,
  buildSection7DetailMarkdown,
  injectSection7Detail,
  SECTION7_HEADING_RE,
};
