const PDFDocument = require('pdfkit');
const { tokenizeInline, parseBlockToken } = require('./richContent');

// Resolves with a Buffer of the generated PDF (no disk I/O — Render is ephemeral).
// `logoBuffer` (Buffer|null) is embedded in the header; `appendixPhotos` is the
// Photo Documentation appendix — callers pre-download these from Firebase Storage.
const generatePDF = async (report, options = {}) => {
  return new Promise((resolve, reject) => {
    try {
      const {
        // Phase 31 (Liability Investigation Report): cover title + Table of
        // Contents labels only -- both default to today's generic text when
        // unset, so every other document type is unaffected. Found via a
        // real end-to-end generation: the ToC used to be hardcoded to the
        // generic 9 section titles regardless of what the report actually
        // contained, so a Liability report's ToC didn't match its own body.
        reportTitle = 'INSURANCE INSPECTION REPORT',
        tocSections = [
          'Section 1: Report Info',
          'Section 2: Claim Info & Insured Info',
          'Section 3: Property Info',
          'Section 4: Inspection Details & Overview',
          'Section 5: Area Observations',
          'Section 6: Scope of Work',
          'Section 7: Estimated Loss Summary',
          'Section 8: Photo Documentation',
          'Section 9: Additional Notes & Conclusion',
        ],
        logoBuffer = null,
        companyName = 'FlacronAI',
        primaryColor = [253, 68, 3],
        watermark = false,
        watermarkText = 'Generated by FlacronAI — Upgrade to remove watermark',
        reportFooter = null,
        hideFlacronBranding = false,
        // Phase 9: photoId -> { buffer, mimeType } for `![[photo:ID|caption]]`
        // and photo-grid tokens the rich editor can insert into section content.
        photoMap = {},
        // Phase 11 (Export Options Modal & PDF Layout Completion)
        includeCoverPage = true,
        includePhotoCaptions = true,
        includePageNumbers = true,
        includeCompanyBranding = true,
        photoLayout = 2,
        // { buffer, mimeType, caption, location, observation }[] -- the
        // "Photo Documentation" appendix. Empty when the caller disabled it
        // (includeAppendix=false) or the report has no images.
        appendixPhotos = [],
        confidentialityStatement = 'CONFIDENTIAL — For authorized recipients only. Contains privileged claim information.',
      } = options;

      const accentHex =
        '#' + primaryColor.map((v) => Math.round(v).toString(16).padStart(2, '0')).join('');
      const NAVY = '#002A64';

      const doc = new PDFDocument({
        margins: { top: 62, bottom: 0, left: 50, right: 50 },
        size: 'LETTER',
        autoFirstPage: false,
        bufferPages: true, // key: buffer all pages for post-processing
        info: {
          Title: `${reportTitle} — ${report.claimNumber || 'N/A'}`,
          Author: companyName,
          Subject: `${report.lossType || ''} — ${report.reportType || ''}`,
          Creator: hideFlacronBranding ? companyName : 'FlacronAI',
        },
      });

      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Ensure every auto-flow page starts content below the header band
      doc.on('pageAdded', () => {
        doc.y = 62;
      });

      const pageWidth = 612;
      const pageHeight = 792;
      const margin = 50;
      const contentWidth = pageWidth - margin * 2;

      // ── helper: add a content page (white body, header/footer added later) ──
      const addPage = () => {
        doc.addPage();
        doc.y = 62; // content starts below the header band (drawn in post-process)
      };

      // ── helper: ensure space on current page ──────────────────────────────
      const ensureSpace = (needed = 80) => {
        if (doc.y > pageHeight - 32 - needed) {
          addPage();
        }
      };

      // ── TABLE state ───────────────────────────────────────────────────────
      let inTable = false;
      let tableRows = [];

      const flushTable = () => {
        if (tableRows.length === 0) return;
        const cols = tableRows[0].length;

        // Fixed column widths: 3-col tables get Category 25% / Description 50% / Cost 25%
        let colWidths;
        if (cols === 3) {
          const q = Math.floor(contentWidth * 0.25);
          colWidths = [q, contentWidth - q * 2, q];
        } else {
          const w = Math.floor(contentWidth / Math.max(cols, 1));
          colWidths = Array(cols).fill(w);
          colWidths[cols - 1] = contentWidth - w * (cols - 1);
        }

        const calcRowHeight = (row) => {
          doc.fontSize(9);
          let h = 28;
          row.forEach((cell, ci) => {
            const cellH =
              doc.heightOfString(stripMd(cell.trim()), { width: colWidths[ci] - 8 }) + 14;
            if (cellH > h) h = cellH;
          });
          return h;
        };

        const drawRow = (row, ri, rowY) => {
          const isTotalRow = ri > 0 && row.some((c) => /total/i.test(c));
          const bg = ri === 0 ? NAVY : isTotalRow ? '#1e293b' : ri % 2 === 0 ? '#f8fafc' : 'white';
          const rowH = calcRowHeight(row);
          doc.rect(margin, rowY, contentWidth, rowH).fill(bg);
          doc
            .fontSize(9)
            .fillColor(ri === 0 || isTotalRow ? 'white' : '#1e293b')
            .font(ri === 0 || isTotalRow ? 'Helvetica-Bold' : 'Helvetica');
          let xPos = margin;
          row.forEach((cell, ci) => {
            doc.text(stripMd(cell.trim()), xPos + 4, rowY + 7, { width: colWidths[ci] - 8 });
            xPos += colWidths[ci];
          });
          return rowH;
        };

        const headerRow = tableRows[0];

        tableRows.forEach((row, ri) => {
          const rowH = calcRowHeight(row);
          // Page break check — never split a row across pages
          if (doc.y + rowH > pageHeight - 32 - 8) {
            addPage();
            // Repeat header on new page for non-header rows
            if (ri > 0) {
              const hdrH = calcRowHeight(headerRow);
              const hdrY = doc.y;
              drawRow(headerRow, 0, hdrY);
              doc.y = hdrY + hdrH;
            }
          }
          const rowY = doc.y;
          const rowH2 = drawRow(row, ri, rowY);
          doc.y = rowY + rowH2;
        });

        doc.y += 6;
        tableRows = [];
        inTable = false;
      };

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 1 — COVER (pixel-matched to the client's reference sample: white
      // page, navy title, thin orange rule, plain label/value list). Phase 11:
      // optional -- toggled off, the document starts at the Table of Contents
      // page instead, which then also becomes the one exempted from the
      // post-process header/footer pass (see `coverPageIndex` below).
      // ══════════════════════════════════════════════════════════════════════
      const cx = pageWidth / 2;
      if (includeCoverPage) {
        doc.addPage(); // manual add; no header/footer yet
        doc.rect(0, 0, pageWidth, pageHeight).fill('white');
        doc.rect(0, 0, pageWidth, 6).fill(accentHex);

        let coverY = 60;

        if (includeCompanyBranding && logoBuffer) {
          try {
            doc.image(logoBuffer, cx - 50, coverY, { width: 100, fit: [100, 50] });
            coverY += 62;
          } catch (err) {
            console.warn(
              `[PDF Export] cover logo embed failed for report ${report?.id || 'unknown'} (${err?.constructor?.name || 'Error'}) -- omitted`
            );
          }
        }

        // Title block — centered, matching the client's reference sample
        if (includeCompanyBranding) {
          doc
            .fontSize(10)
            .fillColor(accentHex)
            .font('Helvetica-Bold')
            .text(hideFlacronBranding ? companyName.toUpperCase() : 'FLACRONAI', margin, coverY, {
              width: contentWidth,
              align: 'center',
              characterSpacing: 2,
            });
          coverY += 26;
        }

        doc
          .fontSize(26)
          .fillColor(NAVY)
          .font('Helvetica-Bold')
          .text(reportTitle, margin, coverY, {
            width: contentWidth,
            align: 'center',
          });
        coverY = doc.y + 8;
        doc.rect(cx - 95, coverY, 190, 2).fill(accentHex);
        coverY += 16;

        // Draft/final status badge — mirrors the app's own draft/finalized concept
        if ((report.status || 'draft') !== 'finalized') {
          doc
            .fontSize(11)
            .fillColor(accentHex)
            .font('Helvetica-Bold')
            .text('DRAFT — PENDING ADJUSTER REVIEW', margin, coverY, {
              width: contentWidth,
              align: 'center',
              characterSpacing: 0.5,
            });
          coverY = doc.y + 22;
        } else {
          coverY += 10;
        }

        const statusLabel =
          {
            draft: 'Draft — pending adjuster review',
            finalized: 'Finalized — approved by licensed adjuster',
          }[report.status] || 'Draft — pending adjuster review';

        const details = [
          ['Report Type', report.reportType || 'Initial'],
          ['Claim Number', report.claimNumber || ''],
          ['Insured Name', report.insuredName || ''],
          ['Insured Email', report.insuredEmail || ''],
          ['Property Address', report.propertyAddress || ''],
          ['Date of Loss', report.lossDate || ''],
          ['Loss Type', report.lossType || ''],
          [
            'Report Date',
            new Date().toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            }),
          ],
          ['Prepared With', hideFlacronBranding ? companyName : 'FlacronAI (FLACRON ENGINE)'],
          ['Status', statusLabel],
        ];

        // Field list — centered as a block, label/value columns matching the sample
        const labelWidth = 150;
        const blockWidth = 420;
        const blockX = cx - blockWidth / 2;
        details.forEach(([label, value]) => {
          const rowY = coverY;
          doc
            .fontSize(10)
            .fillColor(NAVY)
            .font('Helvetica-Bold')
            .text(label, blockX, rowY, { width: labelWidth, lineBreak: false });
          doc
            .fontSize(10)
            .fillColor('#374151')
            .font('Helvetica')
            .text(value || '—', blockX + labelWidth, rowY, { width: blockWidth - labelWidth });
          coverY = Math.max(doc.y, rowY + 20) + 6;
        });

        coverY += 20;
        if (includeCompanyBranding) {
          doc
            .fontSize(8)
            .fillColor('#94a3b8')
            .font('Helvetica-Oblique')
            .text(
              hideFlacronBranding ? `Prepared by ${companyName}` : 'Prepared with the FLACRON ENGINE',
              margin,
              coverY,
              { width: contentWidth, align: 'center' }
            );
        }
      }

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 2 — TABLE OF CONTENTS
      // ══════════════════════════════════════════════════════════════════════
      doc.addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');

      doc.fontSize(20).fillColor(NAVY).font('Helvetica-Bold').text('Table of Contents', margin, 72);
      doc.rect(margin, 97, contentWidth, 2).fill(accentHex);

      tocSections.forEach((sec, i) => {
        const y = 108 + i * 34;
        doc.rect(margin, y, contentWidth, 30).fill(i % 2 === 0 ? '#f8fafc' : 'white');
        doc
          .fontSize(10)
          .fillColor('#1e293b')
          .font('Helvetica')
          .text(sec, margin + 12, y + 9, { width: contentWidth - 60 });
        doc
          .fontSize(9)
          .fillColor('#94a3b8')
          .text(`${i + 3}`, margin + contentWidth - 40, y + 9, { width: 30, align: 'right' });
      });

      // ══════════════════════════════════════════════════════════════════════
      // PAGE 3+ — REPORT CONTENT
      // ══════════════════════════════════════════════════════════════════════
      addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');

      const content = report.content || '';
      const lines = content.split('\n');
      let currentSectionTitle = '';
      let numberedCounter = 0;

      // helper: strip markdown bold/italic/code safely (used only where inline
      // runs aren't rendered individually, e.g. table cells / height math)
      const stripMd = (t) =>
        t
          .replace(/\*\*(.*?)\*\*/g, (_, g) => g)
          .replace(/\*(.*?)\*/g, (_, g) => g)
          .replace(/`(.*?)`/g, (_, g) => g);

      // Phase 9: draws one line's inline bold/italic/underline runs as a
      // single flowed paragraph, using PDFKit's native `continued`/`underline`
      // text options so wrapping still works correctly across runs.
      const drawRuns = (text, x, y, width, { fontSize = 10, color = '#374151' } = {}) => {
        const runs = tokenizeInline(text);
        if (!runs.length) return;
        doc.fontSize(fontSize).fillColor(color);
        runs.forEach((run, i) => {
          const bold = run.bold;
          const italic = run.italic;
          doc.font(
            bold && italic
              ? 'Helvetica-BoldOblique'
              : bold
                ? 'Helvetica-Bold'
                : italic
                  ? 'Helvetica-Oblique'
                  : 'Helvetica'
          );
          const isLast = i === runs.length - 1;
          if (i === 0) {
            doc.text(run.text, x, y, { continued: !isLast, underline: run.underline, width });
          } else {
            doc.text(run.text, { continued: !isLast, underline: run.underline });
          }
        });
      };

      // Phase 9: single photo / photo-grid tokens the rich editor can insert
      // into section content. `photoMap[photoId]` is pre-downloaded by the
      // export route; a missing/failed download degrades to a labeled
      // placeholder box rather than breaking the export.
      const drawSinglePhoto = (photoId, caption) => {
        ensureSpace(210);
        const boxW = Math.min(320, contentWidth);
        const boxH = 190;
        const x = margin + (contentWidth - boxW) / 2;
        const y = doc.y + 6;
        doc.rect(x, y, boxW, boxH).fill('#f8fafc').stroke('#e2e8f0');
        const entry = photoMap[photoId];
        if (entry?.buffer) {
          try {
            doc.image(entry.buffer, x + 4, y + 4, {
              fit: [boxW - 8, boxH - 8],
              align: 'center',
              valign: 'center',
            });
          } catch (err) {
            console.warn(
              `[PDF Export] photo ${photoId} embed failed for report ${report?.id || 'unknown'} (${err?.constructor?.name || 'Error'}) -- using placeholder`
            );
            doc
              .fontSize(8)
              .fillColor('#94a3b8')
              .font('Helvetica')
              .text('Image unavailable', x, y + boxH / 2 - 5, {
                width: boxW,
                align: 'center',
                lineBreak: false,
              });
          }
        } else {
          doc
            .fontSize(8)
            .fillColor('#94a3b8')
            .font('Helvetica')
            .text('Photo unavailable', x, y + boxH / 2 - 5, {
              width: boxW,
              align: 'center',
              lineBreak: false,
            });
        }
        doc.y = y + boxH + 4;
        if (caption) {
          doc
            .fontSize(8)
            .fillColor('#64748b')
            .font('Helvetica')
            .text(stripMd(caption), margin, doc.y, { width: contentWidth, align: 'center' });
        }
        doc.y += 10;
      };

      const drawPhotoGrid = (cols, items) => {
        if (!items.length) return;
        const colGap = 10;
        const colW = (contentWidth - colGap * (cols - 1)) / cols;
        const imgH = 150;
        ensureSpace(imgH + 30);
        let col = 0;
        let rowY = doc.y + 6;
        items.forEach((it) => {
          if (col === 0 && rowY + imgH + 22 > pageHeight - 32) {
            addPage();
            rowY = doc.y + 6;
          }
          const x = margin + col * (colW + colGap);
          doc.rect(x, rowY, colW, imgH).fill('#f8fafc').stroke('#e2e8f0');
          const entry = photoMap[it.photoId];
          if (entry?.buffer) {
            try {
              doc.image(entry.buffer, x + 3, rowY + 3, {
                fit: [colW - 6, imgH - 6],
                align: 'center',
                valign: 'center',
              });
            } catch (err) {
              // placeholder box remains visible
              console.warn(
                `[PDF Export] grid photo ${it.photoId} embed failed for report ${report?.id || 'unknown'} (${err?.constructor?.name || 'Error'}) -- using placeholder`
              );
            }
          } else {
            doc
              .fontSize(7)
              .fillColor('#94a3b8')
              .font('Helvetica')
              .text('Unavailable', x, rowY + imgH / 2 - 4, {
                width: colW,
                align: 'center',
                lineBreak: false,
              });
          }
          if (it.caption) {
            doc
              .fontSize(7)
              .fillColor('#64748b')
              .font('Helvetica')
              .text(stripMd(it.caption), x, rowY + imgH + 3, {
                width: colW,
                align: 'center',
                lineBreak: false,
              });
          }
          col += 1;
          if (col >= cols) {
            col = 0;
            rowY += imgH + 22;
          }
        });
        doc.y = col === 0 ? rowY + 6 : rowY + imgH + 28;
      };

      for (let li = 0; li < lines.length; li++) {
        const line = lines[li];
        const trimmedLine = line.trim();
        const token = parseBlockToken(line);

        // Photo grid — consumes lines until the closing [[/photos]] token.
        if (token?.type === 'grid-open') {
          flushTable();
          numberedCounter = 0;
          const items = [];
          li += 1;
          while (li < lines.length) {
            const inner = parseBlockToken(lines[li]);
            if (inner?.type === 'grid-close') break;
            if (inner?.type === 'grid-item')
              items.push({ photoId: inner.photoId, caption: inner.caption });
            li += 1;
          }
          drawPhotoGrid(token.cols, items);
          continue;
        }

        if (token?.type === 'pagebreak') {
          flushTable();
          numberedCounter = 0;
          addPage();
          continue;
        }

        if (token?.type === 'photo') {
          flushTable();
          numberedCounter = 0;
          drawSinglePhoto(token.photoId, token.caption);
          continue;
        }

        // H3+ (###, ####, etc.) — must check before H2 and H1
        if (/^###/.test(trimmedLine)) {
          flushTable();
          numberedCounter = 0;
          ensureSpace(40);
          const title = trimmedLine.replace(/^#+\s*/, '');
          drawRuns(title, margin, doc.y + 5, contentWidth, { fontSize: 11, color: '#1e293b' });
          doc.y += 4;
          continue;
        }

        // H2 — bold navy heading + thin orange underline (matches the client's
        // reference sample; no solid color block behind the text).
        if (/^##/.test(trimmedLine)) {
          flushTable();
          numberedCounter = 0;
          ensureSpace(40);
          const title = stripMd(trimmedLine.replace(/^#+\s*/, ''));
          currentSectionTitle = title;
          doc
            .fontSize(13)
            .fillColor(NAVY)
            .font('Helvetica-Bold')
            .text(title, margin, doc.y + 10, { width: contentWidth });
          doc.rect(margin, doc.y + 4, contentWidth, 2).fill(accentHex);
          doc.y += 14;
          continue;
        }

        // H1
        if (/^#/.test(trimmedLine)) {
          flushTable();
          numberedCounter = 0;
          ensureSpace(50);
          const title = stripMd(trimmedLine.replace(/^#+\s*/, ''));
          doc
            .fontSize(16)
            .fillColor(NAVY)
            .font('Helvetica-Bold')
            .text(title, margin, doc.y + 8, { width: contentWidth });
          doc.rect(margin, doc.y + 2, contentWidth, 1.5).fill(accentHex);
          doc.y += 14;
          continue;
        }

        // Table row
        if (line.startsWith('|')) {
          inTable = true;
          // slice(1,-1) removes the leading/trailing empty strings from | A | B | format
          // then filter only separator lines — preserve empty cells for column alignment
          const cells = line
            .split('|')
            .slice(1, -1)
            .filter((c) => !c.trim().match(/^[-:]+$/));
          if (cells.length > 0) tableRows.push(cells);
          continue;
        }

        // Skip blank lines inside a table — don't flush mid-table
        // (table is flushed properly when non-table content is encountered below)
        if (inTable && trimmedLine === '') {
          continue;
        }

        // Flush table on any non-table content
        if (inTable) {
          flushTable();
        }

        // HR
        if (line.trim() === '---') {
          numberedCounter = 0;
          ensureSpace(20);
          doc.rect(margin, doc.y + 6, contentWidth, 1).fill('#e2e8f0');
          doc.y += 16;
          continue;
        }

        // Numbered list item (Phase 9)
        if (token?.type === 'numbered') {
          ensureSpace(20);
          numberedCounter += 1;
          drawRuns(`${numberedCounter}.  ${token.text}`, margin + 12, doc.y + 2, contentWidth - 12);
          continue;
        }

        // Bullet — within Report Info / Claim Info & Insured Info specifically,
        // "Label: Value" items render as a bold label + plain value with no
        // bullet dot, matching the client's reference sample's field-list style.
        // Scoped to just these two sections so mixed-content lists elsewhere
        // (e.g. Conclusion) don't end up with an inconsistent dot/no-dot mix.
        if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
          numberedCounter = 0;
          ensureSpace(20);
          const raw = trimmedLine.slice(2);
          const isFieldListSection = /report info|claim info|insured info/i.test(
            currentSectionTitle
          );
          const kv = isFieldListSection ? raw.match(/^([^:]{2,60}):\s*(.*)$/) : null;
          if (kv) {
            const [, label, value] = kv;
            doc
              .fontSize(10)
              .fillColor(NAVY)
              .font('Helvetica-Bold')
              .text(stripMd(label) + ':  ', margin + 2, doc.y + 3, {
                continued: true,
                width: contentWidth - 2,
              });
            doc.font('Helvetica').fillColor('#374151').text(stripMd(value));
          } else {
            drawRuns(`•  ${raw}`, margin + 12, doc.y + 2, contentWidth - 12);
          }
          continue;
        }

        // Blank line
        if (trimmedLine === '') {
          numberedCounter = 0;
          if (doc.y + 5 > pageHeight - 32) addPage();
          else doc.y += 5;
          continue;
        }

        // Regular paragraph
        numberedCounter = 0;
        if (trimmedLine) {
          ensureSpace(20);
          drawRuns(line, margin, doc.y + 2, contentWidth);
        }
      }

      flushTable(); // flush any remaining table

      // ══════════════════════════════════════════════════════════════════════
      // PHOTO APPENDIX (Phase 11) — configurable 1/2/4-photos-per-page
      // layout; each cell shows the photo number, caption, area/location, and
      // the reviewer-approved observation (Phase 8's edit/approve/exclude
      // state, already resolved by the caller into `appendixPhotos`).
      // ══════════════════════════════════════════════════════════════════════
      if (appendixPhotos.length > 0) {
        addPage();
        doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');

        // Section header
        const hdrY = doc.y + 10;
        doc
          .fontSize(13)
          .fillColor(NAVY)
          .font('Helvetica-Bold')
          .text('PHOTO DOCUMENTATION', margin, hdrY, { width: contentWidth, lineBreak: false });
        doc.rect(margin, doc.y + 4, contentWidth, 2).fill(accentHex);
        doc.y += 18;

        const cols = photoLayout;
        const colGap = 12;
        const colW = (contentWidth - colGap * (cols - 1)) / cols;
        const imgH = cols === 1 ? 220 : cols === 2 ? 160 : 100;
        const smallFont = cols === 4 ? 6.5 : 7.5;
        const obsFont = cols === 4 ? 6.5 : 8;
        const minTextH = cols === 4 ? 26 : 40;

        // Pure measurement (doesn't move doc.y) -- lets a whole row's height
        // be known before anything is drawn, so it can page-break cleanly.
        const cellTextHeight = (item) => {
          let h = 2;
          if (includePhotoCaptions && item.caption) {
            doc.fontSize(smallFont);
            h += doc.heightOfString(item.caption, { width: colW - 6 }) + 2;
          }
          if (item.location) {
            doc.fontSize(smallFont);
            h += doc.heightOfString(`Area: ${item.location}`, { width: colW - 6 }) + 2;
          }
          doc.fontSize(obsFont);
          h += doc.heightOfString(item.observation || 'No reviewed observation available.', {
            width: colW - 6,
          });
          return h;
        };

        const rows = [];
        for (let i = 0; i < appendixPhotos.length; i += cols) {
          rows.push(appendixPhotos.slice(i, i + cols).map((p, ci) => ({ ...p, number: i + ci + 1 })));
        }

        rows.forEach((row) => {
          const rowTextH = Math.max(minTextH, ...row.map(cellTextHeight));
          const rowH = 12 + imgH + 6 + rowTextH;
          if (doc.y + rowH > pageHeight - 32) {
            addPage();
          }
          const rowY = doc.y;

          row.forEach((item, ci) => {
            const x = margin + ci * (colW + colGap);
            doc
              .fontSize(8)
              .fillColor(NAVY)
              .font('Helvetica-Bold')
              .text(`Photo ${item.number}`, x, rowY, { width: colW, lineBreak: false });

            const imgY = rowY + 12;
            doc.rect(x, imgY, colW, imgH).fill('#f8fafc').stroke('#e2e8f0');
            try {
              doc.image(item.buffer, x + 3, imgY + 3, {
                fit: [colW - 6, imgH - 6],
                align: 'center',
                valign: 'center',
              });
            } catch (err) {
              console.warn(
                `[PDF Export] appendix photo ${item.number} embed failed for report ${report?.id || 'unknown'} (${err?.constructor?.name || 'Error'}) -- using placeholder`
              );
              doc
                .fontSize(7)
                .fillColor('#94a3b8')
                .font('Helvetica')
                .text('Image unavailable', x, imgY + imgH / 2 - 4, {
                  width: colW,
                  align: 'center',
                  lineBreak: false,
                });
            }

            let textY = imgY + imgH + 4;
            if (includePhotoCaptions && item.caption) {
              doc
                .fontSize(smallFont)
                .fillColor('#374151')
                .font('Helvetica-Bold')
                .text(item.caption, x, textY, { width: colW });
              textY = doc.y + 1;
            }
            if (item.location) {
              doc
                .fontSize(smallFont)
                .fillColor('#64748b')
                .font('Helvetica-Oblique')
                .text(`Area: ${item.location}`, x, textY, { width: colW });
              textY = doc.y + 1;
            }
            if (item.observation) {
              doc
                .fontSize(obsFont)
                .fillColor('#374151')
                .font('Helvetica')
                .text(item.observation, x, textY, { width: colW });
            } else {
              doc
                .fontSize(obsFont)
                .fillColor('#94a3b8')
                .font('Helvetica-Oblique')
                .text('No reviewed observation available.', x, textY, { width: colW });
            }
          });

          doc.y = rowY + rowH + 10;
        });
      }

      // ══════════════════════════════════════════════════════════════════════
      // SIGNATURE PAGE
      // ══════════════════════════════════════════════════════════════════════
      addPage();
      doc.rect(0, 42, pageWidth, pageHeight - 74).fill('white');
      doc.y = 72;

      doc
        .fontSize(18)
        .fillColor(NAVY)
        .font('Helvetica-Bold')
        .text('Reviewing Adjuster Sign-Off', margin, 72);
      doc.rect(margin, 96, contentWidth, 2).fill(accentHex);
      doc.y = 114;

      doc
        .fontSize(10)
        .fillColor('#374151')
        .font('Helvetica')
        .text(
          'This report was prepared with the FLACRON ENGINE and is provided as a draft for professional review. ' +
            'It does not constitute a final determination of cause, coverage, liability, or loss value. ' +
            'The reviewing adjuster’s signature below indicates that they have reviewed, corrected as needed, and approved its contents.',
          margin,
          doc.y,
          { width: contentWidth }
        );

      doc.y += 50;
      // If the adjuster e-signed on approval, render their typed signature + date;
      // otherwise leave blank lines for a wet/manual signature.
      const sig = report.signature;
      const sigDate = sig?.confirmedAt ? new Date(sig.confirmedAt).toLocaleDateString() : '';
      const sigBaseY = doc.y;
      [
        ['Adjuster Signature', margin, sig?.name || '', 'signature'],
        ['Date', margin + 310, sigDate, 'date'],
      ].forEach(([label, x, value]) => {
        if (value) {
          doc
            .fontSize(13)
            .fillColor('#0f172a')
            .font('Helvetica-Oblique')
            .text(value, x, sigBaseY + 14, { width: 210, lineBreak: false });
        }
        doc.rect(x, sigBaseY + 36, 210, 1).fill('#374151');
        doc
          .fontSize(8)
          .fillColor('#94a3b8')
          .font('Helvetica')
          .text(label, x, sigBaseY + 42, { width: 210 });
      });
      if (sig?.name) {
        doc
          .fontSize(8)
          .fillColor('#94a3b8')
          .font('Helvetica')
          .text(
            `Electronically signed by ${sig.name}${sig.title ? `, ${sig.title}` : ''}${sig.confirmedAt ? ` on ${new Date(sig.confirmedAt).toLocaleString()}` : ''}.`,
            margin,
            sigBaseY + 64,
            { width: contentWidth }
          );
      }

      doc.y += 90;
      let fieldY = doc.y;
      [
        ['Adjuster Name (Print)', sig?.name],
        ['License Number', sig?.licenseNumber],
        ['License State', sig?.licenseState],
        ['Company / Firm Name', sig?.company],
        ['Report Version Approved', report.versionApproved],
      ].forEach(([label, value]) => {
        if (value) {
          doc
            .fontSize(10)
            .fillColor('#0f172a')
            .font('Helvetica')
            .text(String(value), margin, fieldY + 12, { width: contentWidth, lineBreak: false });
        }
        doc.rect(margin, fieldY + 30, contentWidth, 1).fill('#374151');
        doc
          .fontSize(8)
          .fillColor('#94a3b8')
          .text(label, margin, fieldY + 36, { width: contentWidth });
        fieldY += 62;
      });
      doc.y = fieldY;

      // ══════════════════════════════════════════════════════════════════════
      // POST-PROCESS: add header/footer to every page except the cover
      // ══════════════════════════════════════════════════════════════════════
      const range = doc.bufferedPageRange();

      // The cover page (when rendered) has its own dark/white design and is
      // exempt from the header/footer pass below; with the cover disabled,
      // the Table of Contents becomes page index 0 and gets a normal header/footer.
      const coverPageIndex = includeCoverPage ? 0 : -1;

      for (let i = 0; i < range.count; i++) {
        doc.switchToPage(range.start + i);
        doc.y = 0; // prevent post-process text() from triggering auto-page-add

        const pgNum = i + 1;

        if (i === coverPageIndex) continue;

        // Watermark
        if (watermark) {
          doc.save();
          doc.opacity(0.06);
          doc.fontSize(22).fillColor('#888888').font('Helvetica');
          for (let wy = 100; wy < pageHeight - 100; wy += 160) {
            doc.save();
            doc.rotate(32, { origin: [pageWidth / 2, wy] });
            doc.text(watermarkText, 0, wy, { width: pageWidth, align: 'center', lineBreak: false });
            doc.restore();
          }
          doc.restore();
        }

        // Header bar
        doc.rect(0, 0, pageWidth, 42).fill(accentHex);

        if (includeCompanyBranding) {
          if (logoBuffer) {
            try {
              doc.image(logoBuffer, margin, 7, { height: 26, fit: [110, 26] });
            } catch {
              doc
                .fontSize(13)
                .fillColor('white')
                .font('Helvetica-Bold')
                .text(hideFlacronBranding ? companyName : 'FlacronAI', margin, 14, {
                  width: 200,
                  lineBreak: false,
                });
            }
          } else {
            doc
              .fontSize(13)
              .fillColor('white')
              .font('Helvetica-Bold')
              .text(hideFlacronBranding ? companyName : 'FlacronAI', margin, 14, {
                width: 200,
                lineBreak: false,
              });
          }
        }

        if (pgNum > 1) {
          doc
            .fontSize(9)
            .fillColor('white')
            .font('Helvetica')
            .text(`Claim: ${report.claimNumber || ''}`, pageWidth - 210, 16, {
              width: 160,
              align: 'right',
              lineBreak: false,
            });
        }

        // Footer bar — brand/custom footer text on the first line; claim
        // number + confidentiality statement (Phase 11, always present, not a
        // toggle) on the second; page number on the right when enabled.
        const fy = pageHeight - 32;
        doc.rect(0, fy, pageWidth, 32).fill('#f1f5f9');
        const footerLeft =
          reportFooter ||
          (hideFlacronBranding ? companyName : 'FlacronAI — Insurance Inspection Reports');
        doc
          .fontSize(8)
          .fillColor('#64748b')
          .font('Helvetica')
          .text(footerLeft, margin, fy + 6, { width: contentWidth - 70, lineBreak: false });
        doc
          .fontSize(6.5)
          .fillColor('#94a3b8')
          .font('Helvetica')
          .text(`Claim ${report.claimNumber || ''} — ${confidentialityStatement}`, margin, fy + 18, {
            width: contentWidth - (includePageNumbers ? 70 : 0),
            lineBreak: false,
          });
        if (includePageNumbers) {
          doc
            .fontSize(8)
            .fillColor('#64748b')
            .font('Helvetica')
            .text(`Page ${pgNum}`, margin + contentWidth - 60, fy + 10, {
              width: 60,
              align: 'right',
              lineBreak: false,
            });
        }
      }

      doc.flushPages();
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generatePDF };
