// Single authoritative source for whether/what watermark an export gets.
// Golden Rule #3 (human review gate) + client-confirmed policy (2026-09-18):
// an un-reviewed draft is ALWAYS watermarked "DRAFT" regardless of tier, and
// approval only ever removes the DRAFT mark -- a free/Starter report keeps
// the FlacronAI branding watermark after approval; only a paid tier with
// `watermark: false` exports clean. Every export surface (PDF overlay, DOCX,
// HTML/preview) must call this instead of recomputing the rule inline.

const DRAFT_TEXT = 'DRAFT — PENDING ADJUSTER REVIEW';
const BRANDING_TEXT = 'Generated by FlacronAI — Upgrade to remove watermark';

// Legacy reports saved before the review gate existed used 'completed'.
// 'approved' is a legacy synonym for the canonical 'finalized' status that
// POST /:id/approve itself writes. All three are treated as reviewed.
const REVIEWED_STATUSES = new Set(['finalized', 'approved', 'completed']);

/**
 * @param {{ reportStatus: string|null|undefined, tierWatermark: boolean }} params
 *   `reportStatus` must be the authoritative, server-persisted report status
 *   (never a client-supplied field). `tierWatermark` must be the server-side
 *   tier config's `watermark` flag (backend/config/tiers.js), never a
 *   client-supplied entitlement claim.
 * @returns {{ show: boolean, kind: 'draft'|'branding'|'none', text: string|null }}
 */
function resolveWatermarkPolicy({ reportStatus, tierWatermark }) {
  const reviewed = REVIEWED_STATUSES.has(reportStatus);

  if (!reviewed) {
    // Missing/unknown status fails safe as unreviewed -- REVIEWED_STATUSES.has()
    // is false for undefined/null/any unrecognized value.
    return { show: true, kind: 'draft', text: DRAFT_TEXT };
  }

  if (tierWatermark) {
    return { show: true, kind: 'branding', text: BRANDING_TEXT };
  }

  return { show: false, kind: 'none', text: null };
}

module.exports = { resolveWatermarkPolicy, REVIEWED_STATUSES, DRAFT_TEXT, BRANDING_TEXT };
