// Phase 43 (OpenAI Preliminary Pricing Service) -- pure workflow/merge logic
// for the "Generate Preliminary Pricing" feature inside CanonicalEstimateEditor
// (ReportPreviewPage.jsx). Follows the exact convention canonicalEstimateEditor
// .js itself established (Phase 42, 2026-09-18 correction): every piece of
// logic that doesn't strictly require a live DOM lives here as a pure,
// directly-unit-tested function (no @testing-library/react/jsdom exists in
// this repo -- see canonicalEstimateEditor.test.js's own header comment).
//
// Trust-boundary correction (2026-09-19): a proposal item from the server
// NEVER carries `providerModel` at all any more (pricingService.js strips
// it before the HTTP response) -- there is nothing to accidentally render.
// Audit metadata now survives the accept -> apply -> save round trip a
// different way: this module stamps each merged draft line item with the
// OPAQUE `appliedProposalId`/`appliedSuggestionId` handles (never a raw
// provider/model string), and canonicalEstimateEditor.js's
// buildCanonicalEstimatePayload sends those back as `appliedProposal` --
// the server independently re-verifies them against its own short-lived
// proposal record (backend/utils/pricingProposalStore.js) and injects the
// TRUSTED providerModel itself; the client never asserts it directly. Every
// user-visible label stays exactly "Pricing Source generated by: Flacron
// Engine" / "Status: Preliminary / Editable", per Golden Rule #1/#2.
import { emptyCanonicalLineItem, newStableId } from './canonicalEstimateEditor';

const CAP = { room: 100, damageType: 100, repairAction: 60, description: 300, material: 150, tradeOrCategory: 60 };
const clean = (v, maxLen) => String(v ?? '').trim().slice(0, maxLen);

// Builds the POST /:id/estimate-detail/price-suggestions request body from
// the editor's own draft state. `targets` is an array of either an existing
// draft line item (targeted for re-pricing) or a small ad-hoc "new item"
// scope object the user fills in before generating -- both already have the
// same room/damageType/repairAction/description/material/quantity/unit
// shape the draft line item uses. Only non-PII locale + repair-scope fields
// are ever sent (no insured name/claim number/address street line/photos).
export const buildPriceSuggestionsRequestPayload = ({ locationContext, currency, targets, regenerate }) => ({
  locationContext: {
    country: clean(locationContext?.country, 60),
    state: clean(locationContext?.state, 60),
    city: clean(locationContext?.city, 100),
    postalCode: clean(locationContext?.postalCode, 20),
  },
  currency: (currency || 'USD').trim().toUpperCase(),
  regenerate: regenerate === true,
  items: targets.map((t) => ({
    targetLineItemId: t.targetLineItemId ?? null,
    room: clean(t.room, CAP.room),
    damageType: clean(t.damageType, CAP.damageType),
    repairAction: clean(t.repairAction, CAP.repairAction),
    description: clean(t.description, CAP.description),
    material: clean(t.material, CAP.material),
    trade: clean(t.trade, CAP.tradeOrCategory),
    category: clean(t.category, CAP.tradeOrCategory),
    quantity: Number(t.quantity),
    unit: t.unit,
  })),
});

// Client-side pre-check mirroring the server's own required-field
// validation (pricingService.js's validatePricingRequestBody) -- fast
// feedback only; the server independently re-validates.
export const validatePriceSuggestionsRequest = ({ locationContext, targets }) => {
  if (!clean(locationContext?.country, 60)) return 'A country is required to generate preliminary pricing.';
  if (!targets || targets.length === 0) return 'Select at least one item to price.';
  for (const t of targets) {
    if (!clean(t.room, CAP.room)) return 'Every item needs a room/area before pricing it.';
    if (!clean(t.description, CAP.description)) return 'Every item needs a description before pricing it.';
    if (!(Number(t.quantity) > 0)) return 'Every item needs a positive quantity before pricing it.';
  }
  return null;
};

// Classifies a failed POST .../price-suggestions axios error into exactly
// one state the UI branches on -- same pattern as
// classifyCanonicalEstimateSaveError in canonicalEstimateEditor.js.
export const classifyPriceSuggestionsError = (err) => {
  if (err?.name === 'CanceledError' || err?.code === 'ERR_CANCELED') {
    return { kind: 'cancelled', message: 'Cancelled.' };
  }
  const data = err?.response?.data;
  const status = err?.response?.status;
  if (!err?.response) {
    return { kind: 'network', message: 'Network error -- check your connection, then Retry.' };
  }
  if (data?.code === 'PRICING_PROVIDER_UNAVAILABLE') {
    return { kind: 'unavailable', message: 'Preliminary pricing is not currently available.' };
  }
  if (data?.code === 'PRICING_TIMEOUT') {
    return { kind: 'retryable', message: data.error || 'The pricing provider timed out. Please try again.' };
  }
  if (data?.code === 'PRICING_RATE_LIMITED' || data?.code === 'PRICING_LIMIT_EXCEEDED') {
    return { kind: 'rate_limited', message: data.error || 'Please wait a moment and try again.' };
  }
  if (data?.code === 'PRICING_QUOTA_EXCEEDED' || data?.code === 'PRICING_AUTH_FAILED') {
    return { kind: 'config_failure', message: 'Preliminary pricing is temporarily unavailable.' };
  }
  if (data?.code === 'PRICING_MALFORMED_RESPONSE') {
    return { kind: 'retryable', message: 'The pricing provider returned an unusable response. Please try again.' };
  }
  if (data?.code === 'VALIDATION_ERROR') {
    return { kind: 'validation', message: data.error, field: data.field };
  }
  if (data?.code === 'REPORT_FINALIZED') {
    return { kind: 'finalized', message: data.error };
  }
  if (status === 403 || status === 404) {
    return { kind: 'unauthorized', message: data?.error || 'You do not have permission to do this.' };
  }
  return { kind: 'unknown', message: data?.error || 'Could not generate preliminary pricing.' };
};

// THE critical safety logic. `existingLineItems`/return value are both in
// canonicalEstimateEditor.js's draft line-item shape (see
// emptyCanonicalLineItem). `proposalId` is the top-level opaque handle from
// the POST .../price-suggestions response; `proposedItems` are that same
// response's items (server shape: room/trade/category/.../materialUnitCost/
// .../suggestionId/targetLineItemId -- NEVER providerModel, stripped
// server-side). `acceptedSuggestionIds` is the set of `suggestionId`s the
// user individually checked "Accept" on -- nothing is ever auto-applied.
//
// Matching rule (in order): a proposal item is matched to an existing draft
// item FIRST by `appliedSuggestionId` (set the first time this exact
// suggestion was applied), THEN by `targetLineItemId` (the item the user
// originally asked to reprice). This is what makes re-generating +
// re-accepting the SAME suggestion idempotent -- it updates the same item
// in place rather than appending a duplicate, whether that item was
// originally an existing line item OR a brand-new one this same suggestion
// previously appended. `appliedProposalId`/`appliedSuggestionId` (opaque
// handles only -- never a provider/model string) are what
// canonicalEstimateEditor.js's buildCanonicalEstimatePayload later reads to
// build the save request's `appliedProposal`; the server independently
// re-verifies them and injects the trusted pricing/providerModel itself
// (see this file's header comment).
//
// Override safety (Golden Rule #4/#7-adjacent -- never silently overwrite a
// user's deliberate manual price): a proposal matched to an existing item
// with `overrideActive === true` is SKIPPED, not merged -- reported back in
// `skipped` so the UI can tell the user why. This is unconditional: even a
// cache-hit proposal (identical fingerprint served instantly, no new
// provider call) goes through this exact same skip check, since nothing is
// ever auto-applied regardless of where the proposal came from. The server
// independently enforces this same rule at save time (a raw API call can't
// bypass it by skipping the UI) -- see canonicalEstimate.js's
// `previousOverrideActive` check.
export const mergeProposedPricingIntoLineItems = (existingLineItems, proposalId, proposedItems, acceptedSuggestionIds) => {
  const accepted = new Set(acceptedSuggestionIds || []);
  const lineItems = [...existingLineItems];
  const applied = [];
  const skipped = [];

  const fieldsFromProposal = (proposal) => ({
    room: proposal.room || '',
    trade: proposal.trade || '',
    category: proposal.category || '',
    damageType: proposal.damageType || '',
    repairAction: proposal.repairAction || '',
    description: proposal.description || '',
    material: proposal.material || '',
    quantity: String(proposal.quantity ?? 1),
    unit: proposal.unit || 'SF',
    materialUnitCost: String(proposal.materialUnitCost ?? 0),
    laborUnitCost: String(proposal.laborUnitCost ?? 0),
    equipmentUnitCost: String(proposal.equipmentUnitCost ?? 0),
    assumptions: proposal.assumptions || '',
    confidence: proposal.confidence || 'medium',
    pricingSource: 'ai_suggested',
    appliedProposalId: proposalId,
    appliedSuggestionId: proposal.suggestionId,
  });

  for (const proposal of proposedItems) {
    if (!accepted.has(proposal.suggestionId)) continue;

    const bySourceIdx = lineItems.findIndex((li) => li.appliedSuggestionId === proposal.suggestionId);
    const byTargetIdx =
      bySourceIdx === -1 && proposal.targetLineItemId
        ? lineItems.findIndex((li) => li.id === proposal.targetLineItemId)
        : -1;
    const idx = bySourceIdx !== -1 ? bySourceIdx : byTargetIdx;

    if (idx !== -1) {
      const existing = lineItems[idx];
      if (existing.overrideActive) {
        skipped.push({ suggestionId: proposal.suggestionId, targetLineItemId: existing.id, reason: 'user_override_active' });
        continue;
      }
      lineItems[idx] = { ...existing, ...fieldsFromProposal(proposal) };
      applied.push({ suggestionId: proposal.suggestionId, targetLineItemId: existing.id, mode: 'merged' });
    } else {
      const newItem = { ...emptyCanonicalLineItem(), id: newStableId('li'), ...fieldsFromProposal(proposal) };
      lineItems.push(newItem);
      applied.push({ suggestionId: proposal.suggestionId, targetLineItemId: newItem.id, mode: 'appended' });
    }
  }

  return { lineItems, applied, skipped };
};

// Duplicate-submission / read-only guard, same shape as
// canStartCanonicalEstimateSave in canonicalEstimateEditor.js.
export const canStartPriceSuggestionsGeneration = ({ generating, readOnly }) => !generating && !readOnly;
